version: 2

sources:
  - name: datamodel_source
    description: "aggregated data from the destination PostgreSQL database."
    database: "{{ env_var('DB_DATABASE') }}"
    schema: "{{ env_var('DB_SCHEMA') }}"
    tables:
      - name: "{{ env_var('TABLE_DM') }}"
        description: "Data Model table for Ad Campaign Data"

  - name: staging_source
    description: "Raw data from the destination PostgreSQL database."
    database: "{{ env_var('DB_DATABASE') }}"
    schema: "{{ env_var('DB_SCHEMA') }}"
    tables:
      - name: "{{ env_var('TABLE_STG') }}"
        description: "Staging table for Ad Campaign Data"
