version: 2

models:
  - name: stg_ad_logs
    columns:
      - name: ad_id
        tests:
          - not_null
      - name: impressions
        tests:
          - not_null
      - name: clicks
        tests:
          - not_null
  - name: campaign_daily_metrics
    columns:
      - name: campaign_id
        tests:
          - not_null
